### ISSUE TITLE
got a long list of errors

### ISSUE THREAD

**Issue by gitguudsun** [Wulfre/e621dl#8]
gnome@gnome-VirtualBox:~/Documents/e621dl-4.1.0$ python3 e621dl.py
Traceback (most recent call last):
  File "e621dl.py", line 18, in <module>
    import colorama
ImportError: No module named 'colorama'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "e621dl.py", line 20, in <module>
    import pip
ImportError: No module named 'pip'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "e621dl.py", line 32, in <module>
    import colorama
ImportError: No module named 'colorama'

**Comment by Wulfre** [comment]
You will need to install pip3, I forgot to include that in the documentation, because I use windows which includes it by default. Apologies.
